development:
  adapter: postgresql
  database: db_dev
  pool: 5
  timeout: 5000
  username: carloslazo
  password:

test:
  adapter: postgresql
  database: db_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db_prod
  pool: 5
  timeout: 5000